### ISSUE TITLE
Skip rep syscall

### ISSUE THREAD

**Issue by seth1002** [zeropointdynamics/zelos#102]
**Is your feature request related to a problem? Please describe.**
Once a rep syscall over 50 times, there is no chance to "reenable syscall printing"? Do i have any option to skip only rep syscalls?

       # Disable syscall printing if lots of repetitions occur
        if (
            self._last_syscall_count <= self.rep_syscall_print_limit
            and self.rep_syscall_print_limit > 0
        ):
            rep_print_limit = self.rep_syscall_print_limit
            syscall_manager = zelos.internal_engine.zos.syscall_manager
            if sysname == self._last_syscall:
                self._last_syscall_count += 1
            else:
                self._last_syscall = sysname
                if self._last_syscall_count > rep_print_limit:
                    self.logger.info(f"Syscall printing reenabled")
                    syscall_manager.should_print_syscalls = True
                self._last_syscall_count = 1

            if self._last_syscall_count == rep_print_limit:
                self.logger.info(
                    f"Syscall {self._last_syscall} called over "
                    f"{rep_print_limit} times. No longer printing syscalls"
                )
                syscall_manager.should_print_syscalls = False

**Comment by kvalakuzhyzp** [comment]
Thanks again for the issue, this problem should be fixed now.
