### ISSUE TITLE
do you have plan to dev a IDA debug plugin?

### ISSUE THREAD

**Issue by seth1002** [zeropointdynamics/zelos#124]
Hi, i think it would be great to dev a IDA debug plugin. do you guys have any plan?

**Comment by valakuzhyk** [comment]
Hi there, apologies for the delayed response.

As you can see, recently there haven't been many extra cycles to develop on Zelos, but we are hoping that should change soon! While we have an Ida plugin that allows [loading an overlay containing a trace](https://zelos.readthedocs.io/en/latest/tutorials/06_snapshot_overlay.html) from Zelos, we haven't yet investigated what it would take to build out an Ida Debug plugin. We welcome any contributions if you have the time!

**Comment by seth1002** [comment]
I've already sent an invitation, can you please check？

**Comment by valakuzhyk** [comment]
Apologies @seth1002, do you mind resending the invite?
