### ISSUE TITLE
Missing libm.so.6 causes zelos to fail

### ISSUE THREAD

**Issue by heymanjm** [zeropointdynamics/zelos#46]
**Describe the bug**
A small prime generator C program that makes use of libm fails because zelos cannot open /lib/x86_64-linux-gnu/x86_64/libm.so.6

**To Reproduce**
1. compile the attached program, 'gcc -o primes primes.c -lm'
2. run 'zelos ./primes'
3. See error

**Expected behavior**
output from the program to show instructions (see attachment 2)

**Screenshots**
[StdErr]: 'bytearray(b'./primes')'
[StdErr]: 'bytearray(b': ')'
[StdErr]: 'bytearray(b'error while loading shared libraries')'
[StdErr]: 'bytearray(b': ')'
[StdErr]: 'bytearray(b'libm.so.6')'
[StdErr]: 'bytearray(b': ')'
[StdErr]: 'bytearray(b'cannot open shared object file')'
[StdErr]: 'bytearray(b': ')'
[StdErr]: 'bytearray(b'Operation not permitted')'
[StdErr]: 'bytearray(b'\n')'
[main] [SYSCALL] writev ( fd=0x2 (stderr), *iov=0xff08dfe0 ("./primes: error while loading shared libraries: libm.so.6: cannot open shared object file: Operation not permitted\n"), iovcnt=0xa ) -> 73

**Additional context**
Attachment 2 was created when I set up a symlink to libm.so.6
Note I'm running on Mageia 6 Linux, a RH derivative.

[primes.c.txt](https://github.com/zeropointdynamics/zelos/files/4606042/primes.c.txt)
[zelos.fixed.txt](https://github.com/zeropointdynamics/zelos/files/4606043/zelos.fixed.txt)

**Comment by rcourt** [comment]
@heymanjm You can fix this by using the `--mount` flag. Using the `--mount` flag, it is possible to specify a file on your local machine to be mounted into the emulated filesystem, in this case **libm.so.6**.

I compiled **primes.c** and ran it with the following:

```sh
zelos ./primes --mount x86_64,/lib/x86_64-linux-gnu/libm.so.6,/lib/x86_64-linux-gnu/libm.so.6
``` 

Output attached
[primes.out.txt](https://github.com/zeropointdynamics/zelos/files/4619018/primes.out.txt)
