### ISSUE TITLE
A short thank you note.

### ISSUE THREAD

**Issue by xwings** [zeropointdynamics/zelos#54]
Hi,

I am the founder and project owner of Qiling Framework. Just incase you never heard of it. Please do pay us a visit at https://qiling.io

Just like to let you know, Qiling's memory management actually "refer/copy/use" some of your code. We did credited zelos in our code. Please refer to:

https://github.com/qilingframework/qiling/blob/dev/qiling/os/memory.py

Thank you for the excellent code and we do really wish can work together in the near future. Again, thank you very much!

**Comment by kzsnow** [comment]
Thanks for the note! Of course we know of your framework, many similarities. We'd be open to some collaboration, where it makes sense, for those mutually beneficial components.

**Comment by xwings** [comment]
Cool! Thanks for the reply.
