### ISSUE TITLE
wrong old_mmap define

### ISSUE THREAD

**Issue by seth1002** [zeropointdynamics/zelos#90]
**Describe the bug**
params copy form user stack space, not via register.... can you please fix this bug?

zelos define
----------------------------------------------
https://github.com/zeropointdynamics/zelos/blob/f670a6288788fe1a0de31725ea1ff58c5f9ea1d2/src/zelos/ext/platforms/linux/syscalls/syscalls.py
def sys_mmap(sm, p):
    args = sm.get_args(
        [
            ("void*", "addr"),
            ("size_t", "length"),
            ("int", "prot"),
            ("int", "flags"),
            ("int", "fd"),
            ("off_t", "offset"),
        ]
    )
    try:
        return mmapx(sm, p, "mmap", args, args.offset)
    except Exception as e:
        sm.print("mmap exception: " + str(e))
        return -1

old_mmap define
-------------------------------------------------
https://github.com/torvalds/linux/blob/a5ad5742f671de906adbf29fbedf0a04705cebad/arch/x86/kernel/sys_ia32.c
COMPAT_SYSCALL_DEFINE1(ia32_mmap, struct mmap_arg_struct32 __user *, arg)
{
	struct mmap_arg_struct32 a;

	if (copy_from_user(&a, arg, sizeof(a)))
		return -EFAULT;

**Comment by rcourt** [comment]
Will be fixed in #91.
