### ISSUE TITLE
MIPS, socket, set_return_value(), set v0 is not enough

### ISSUE THREAD

**Issue by seth1002** [zeropointdynamics/zelos#94]
**Describe the bug**
On MIPS, the wrapper of syscall socket will check reg $a3, so set $v0 as return value is not enough.

IDA dis code:
li      $v0, 0x1057      # __NR_socket
syscall 0
la      $t9, lib___errno_location
beqz    $a3, loc_420404 <---------will check reg $a3
move    $s0, $v0

zelos code:
def set_return_value(self, value):
    self.emu.set_reg("v0", value)

**Comment by kvalakuzhyzp** [comment]
Thanks for using Zelos as well as helping us improve it!
